=== france193/DP2_Assignment_3a-b/target/WEB-INF/classes/xsd/nffgVerifier.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- This XSD file was developed by Francesco Longo for the Assignment 3a-b 
	of the course Distributed Programming II in Politechnic University of Turin. -->

<!-- IN THE APP VERIFY NODE FROM POLICY REFERRING TO A CORRECT NODE OF THE 
	SPECIFED NFFG -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:flo="https://france193.wordpress.com" targetNamespace="https://france193.wordpress.com"
            elementFormDefault="qualified">

    <!-- SINGLE ELEMENT -->
    <!-- nffg -->
    <xsd:element name="FLNffg">
        <xsd:complexType>
            <xsd:sequence>
                <!-- NODE -->
                <xsd:element ref="flo:FLNode" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="optional"/>
            <xsd:attribute name="name" type="flo:name" use="required"/>
            <xsd:attribute name="last_updated_time" type="xsd:dateTime"
                           use="required"/>
        </xsd:complexType>

        <!-- Uniqueness of Link -->
        <xsd:key name="FLLink_nffg_id">
            <xsd:selector xpath="flo:FLNode/flo:FLLink"/>
            <xsd:field xpath="@name"/>
        </xsd:key>

        <!-- Uniqueness of Link -->
        <xsd:key name="FLNode_nffg_id">
            <xsd:selector xpath="flo:FLNode"/>
            <xsd:field xpath="@name"/>
        </xsd:key>

        <!-- in FLLink, destination_node must refers to an existing node -->
        <xsd:keyref name="FLLink_refers_to_node" refer="flo:FLNode_nffg_id">
            <xsd:selector xpath="flo:FLNode/flo:FLLink"/>
            <xsd:field xpath="@destination_node"/>
        </xsd:keyref>

    </xsd:element>

    <!-- node -->
    <xsd:element name="FLNode">
        <xsd:complexType>
            <xsd:sequence>
                <!-- LINK -->
                <xsd:element name="FLLink" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:attribute name="name" type="flo:name" use="required"/>
                        <xsd:attribute name="destination_node" type="xsd:string"
                                       use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="optional"/>
            <xsd:attribute name="name" type="flo:name" use="required"/>
            <xsd:attribute name="functional_type" type="flo:FLNodeFunctionalType"
                           use="optional"/>
        </xsd:complexType>

        <!-- Uniqueness of Link -->
        <xsd:key name="FLLink_id">
            <xsd:selector xpath="flo:FLLink"/>
            <xsd:field xpath="@name"/>
        </xsd:key>

    </xsd:element>

    <!-- policy -->
    <xsd:element name="FLPolicy">
        <xsd:complexType>
            <xsd:sequence>
                <!-- TRAVERSED NODE -->
                <xsd:element name="traversed_node" type="flo:FLNodeFunctionalType"
                             minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="flo:FLVResult" minOccurs="0"
                             maxOccurs="1"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="flo:name" use="required"/>
            <xsd:attribute name="nffg_name" type="xsd:string" use="optional"/>
            <xsd:attribute name="isPositive" type="xsd:boolean"
                           use="optional"/>
            <xsd:attribute name="source_node" type="xsd:string"
                           use="optional"/>
            <xsd:attribute name="destination_node" type="xsd:string"
                           use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <!-- vresult -->
    <xsd:element name="FLVResult">
        <xsd:complexType>
            <xsd:attribute name="policy" type="flo:name" use="required"/>
            <xsd:attribute name="result" type="xsd:boolean" use="optional"/>
            <xsd:attribute name="time" type="xsd:dateTime" use="optional"/>
            <xsd:attribute name="message" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <!-- COLLECTION OF ELEMENTS -->
    <!-- nffgs -->
    <xsd:element name="FLNffgs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="flo:FLNffg" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="flo:FLPolicy" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="flo:FLVResult" minOccurs="0"
                             maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>

        <!-- Uniqueness of Nffg -->
        <xsd:key name="FLNffg_id">
            <xsd:selector xpath="flo:FLNffg"/>
            <xsd:field xpath="@name"/>
        </xsd:key>

        <!-- Uniqueness of FLVResult -->
        <xsd:key name="FLVResult_nffgs_id">
            <xsd:selector xpath="flo:FLVResult"/>
            <xsd:field xpath="@policy"/>
        </xsd:key>

        <!-- Uniqueness of FLPolicy -->
        <xsd:key name="FLPolicy_nffgs_id">
            <xsd:selector xpath="flo:FLPolicy"/>
            <xsd:field xpath="@name"/>
        </xsd:key>

        <!-- in FLPolicy, nffg_name must refers to an existing nffg -->
        <xsd:keyref name="FLPolicy_refers_to_nffg" refer="flo:FLNffg_id">
            <xsd:selector xpath="flo:FLPolicies/flo:FLPolicy"/>
            <xsd:field xpath="@nffg_name"/>
        </xsd:keyref>

        <!-- FLVResult must refers to an existing policy -->
        <xsd:keyref name="FLVResult_nffgs_refers_to_FLPolicy"
                    refer="flo:FLPolicy_nffgs_id">
            <xsd:selector xpath="flo:FLVResult"/>
            <xsd:field xpath="@policy"/>
        </xsd:keyref>

    </xsd:element>

    <!-- nodes -->
    <xsd:element name="FLNodes">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="flo:FLNode" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>

        <!-- Uniqueness of Node -->
        <xsd:key name="FLNode_id">
            <xsd:selector xpath="flo:FLNode"/>
            <xsd:field xpath="@name"/>
        </xsd:key>

    </xsd:element>

    <!-- policies -->
    <xsd:element name="FLPolicies">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="flo:FLPolicy" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="flo:FLVResult" minOccurs="0"
                             maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>

        <!-- Uniqueness of FLPolicy -->
        <xsd:key name="FLPolicy_id">
            <xsd:selector xpath="flo:FLPolicy"/>
            <xsd:field xpath="@name"/>
        </xsd:key>

        <!-- FLVResult must refers to an existing policy -->
        <xsd:keyref name="FLVResult_refers_to_FLPolicy" refer="flo:FLPolicy_id">
            <xsd:selector xpath="flo:FLVResults/flo:FLVResult"/>
            <xsd:field xpath="@policy"/>
        </xsd:keyref>

    </xsd:element>

    <!-- vresults -->
    <xsd:element name="FLVResults">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="flo:FLVResult" minOccurs="0"
                             maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>

        <!-- Uniqueness of FLVResult -->
        <xsd:key name="FLVResult_id">
            <xsd:selector xpath="flo:FLVResult"/>
            <xsd:field xpath="@policy"/>
        </xsd:key>

    </xsd:element>

    <!-- OTHER TYPES -->
    <xsd:simpleType name="FLNodeFunctionalType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="CACHE"/>
            <xsd:enumeration value="DPI"/>
            <xsd:enumeration value="FW"/>
            <xsd:enumeration value="MAIL_CLIENT"/>
            <xsd:enumeration value="MAIL_SERVER"/>
            <xsd:enumeration value="NAT"/>
            <xsd:enumeration value="SPAM"/>
            <xsd:enumeration value="VPN"/>
            <xsd:enumeration value="WEB_CLIENT"/>
            <xsd:enumeration value="WEB_SERVER"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="name">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([A-Z]|[a-z])(\w)+"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== france193/DP2_Assignment_3a-b/custom/FLNodes.xml
<fran:FLNodes xmlns:fran="https://france193.wordpress.com"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://france193.wordpress.com ../xsd/nffgVerifier.xsd">

    <!-- node id must be unique -->

    <!-- link id must be unique in a node (already done) -->

    <fran:FLNode name="node0" functional_type="NAT">
        <fran:FLLink name="link0" destination_node="node1"/>
        <fran:FLLink name="link1" destination_node="node2"/>
    </fran:FLNode>

    <fran:FLNode name="node1" functional_type="MAIL_SERVER">
        <fran:FLLink name="link0" destination_node="node1"/>
        <fran:FLLink name="link1" destination_node="node2"/>
        <fran:FLLink name="link2" destination_node="node3"/>
    </fran:FLNode>

</fran:FLNodes>

=== france193/DP2_Assignment_3a-b/custom/FLNffg.xml
<fran:FLNffg xmlns:fran="https://france193.wordpress.com"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://france193.wordpress.com ../xsd/nffgVerifier.xsd"
             name="nffg0" last_updated_time="2008-09-29T03:49:45">

    <!-- in link, destination_node must refers to an existiong node -->
    <!-- link id must be unique in a nffg -->

    <!-- link id must be unique in a node (already done) -->
    <!-- node id must be unique in nffg (already done) -->

    <fran:FLNode name="node0" functional_type="NAT">
        <fran:FLLink name="link0" destination_node="node1"/>
        <fran:FLLink name="link1" destination_node="node2"/>
    </fran:FLNode>

    <fran:FLNode name="node1" functional_type="MAIL_SERVER">
        <fran:FLLink name="link2" destination_node="node1"/>
        <fran:FLLink name="link3" destination_node="node2"/>
        <fran:FLLink name="link4" destination_node="node3"/>
    </fran:FLNode>

    <fran:FLNode name="node2" functional_type="MAIL_SERVER"/>

    <fran:FLNode name="node3" functional_type="MAIL_SERVER"/>

</fran:FLNffg>

=== france193/DP2_Assignment_3a-b/custom/FLNffgs.xml
<fran:FLNffgs xmlns:fran="https://france193.wordpress.com"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://france193.wordpress.com ../xsd/nffgVerifier.xsd">

    <!-- nffg name must be unique inside nffgs -->
    <!-- in policy, nffg_name must refers to an existing nffg -->

    <!-- policy name must be unique (already done) -->
    <!-- flvresult name must be unique (already done) -->
    <!-- flvresult must refers to an existing policy (already done) -->
    <!-- in link, destination_node must refers to an existiong node (already
        done) -->
    <!-- link id must be unique in a nffg (already done) -->
    <!-- link id must be unique in a node (already done) -->
    <!-- node id must be unique in nffg (already done) -->

    <fran:FLNffg name="nffg0" last_updated_time="2008-09-29T03:49:45">

        <fran:FLNode name="node0" functional_type="NAT">
            <fran:FLLink name="link0" destination_node="node1"/>
        </fran:FLNode>

        <fran:FLNode name="node1" functional_type="MAIL_SERVER">
            <fran:FLLink name="link1" destination_node="node0"/>
            <fran:FLLink name="link2" destination_node="node1"/>
        </fran:FLNode>

    </fran:FLNffg>

    <fran:FLNffg name="nffg1" last_updated_time="2008-09-29T03:49:45">


        <fran:FLNode name="node0" functional_type="NAT">
            <fran:FLLink name="link0" destination_node="node1"/>
        </fran:FLNode>

        <fran:FLNode name="node1" functional_type="MAIL_SERVER">
            <fran:FLLink name="link2" destination_node="node0"/>
            <fran:FLLink name="link3" destination_node="node1"/>
        </fran:FLNode>

    </fran:FLNffg>

    <fran:FLPolicy name="policy0" nffg_name="nffg0"
                   isPositive="false" source_node="node0" destination_node="node1">

        <fran:traversed_node>WEB_CLIENT</fran:traversed_node>
        <fran:traversed_node>DPI</fran:traversed_node>
        <fran:traversed_node>NAT</fran:traversed_node>

    </fran:FLPolicy>

    <fran:FLPolicy name="policy1" nffg_name="nffg1"
                   isPositive="false" source_node="node0" destination_node="node1">
    </fran:FLPolicy>

    <fran:FLVResult policy="policy0" result="false"
                    time="2007-10-26T08:36:28" message="Policy is not verified"/>
    <fran:FLVResult policy="policy1" result="false"
                    time="2007-10-26T08:36:28" message="Policy is not verified"/>

</fran:FLNffgs>
